-- AlterTable
ALTER TABLE "readings" ADD COLUMN     "noise_1k" DOUBLE PRECISION,
ADD COLUMN     "noise_250" DOUBLE PRECISION,
ADD COLUMN     "noise_2k" DOUBLE PRECISION,
ADD COLUMN     "noise_4k" DOUBLE PRECISION,
ADD COLUMN     "noise_500" DOUBLE PRECISION,
ADD COLUMN     "noise_8k" DOUBLE PRECISION,
ADD COLUMN     "noise_low" DOUBLE PRECISION;
